### ISSUE TITLE
Fix weird dialog padding

### ISSUE THREAD

**Issue by silverAndroid** [silverAndroid/tournament-maker#16]
Try and see why there is more padding than should be in the title bar of the dialog

**Comment by yhonHoiy** [comment]
which dialog?

**Comment by silverAndroid** [comment]
All of the dialogs are like that, this is an [example from TournamentCreateActivity](http://imgur.com/8516n4P)

**Comment by yhonHoiy** [comment]
Resolved: The issue is cause by the DialogTheme Style, which is used as an argument in line 44 of the Util Class. For now, I have left the generation of AlertDialog.Builder with default theme. Keep this note in mind

**Comment by silverAndroid** [comment]
Can you commit the change and close the issue? :smile:

**Comment by yhonHoiy** [comment]
trying to do that right now. I keep forgetting my github password
